name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Ensure this matches the exact syntax and versioning scheme expected by setup-dotnet
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal --configuration Release --filter Category=Unit
    - name: Run integration tests
      run: dotnet test --no-build --verbosity normal --configuration Release --filter Category=Integration
